[[Group-API]]
== Group API

[[Group-만들기]]
=== Group 그룹 만들기

operation::group-create/success[snippets='http-request,request-fields,http-response,response-fields']

[[Group-유저리스트조회]]
=== Group 유저 리스트 조회

operation::group-user-list/success[snippets='http-request,path-parameters,http-response,response-fields']

[[Group-반려동물리스트조회]]
=== Group 반려동물 리스트 조회

operation::group-pet-list/success[snippets='http-request,path-parameters,http-response,response-fields']

[[Group-초대하기]]
=== Group 초대하기

operation::group-invite/success[snippets='http-request,path-parameters,request-fields,http-response,response-fields']

[[Group-나오기]]
=== Group 나오기

operation::leave-group/success[snippets='http-request,path-parameters,http-response,response-fields']

[[Group-내보내기]]
=== Group 내보내기

operation::delete-group-member/success[snippets='http-request,path-parameters,http-response,response-fields']

[[Group-리스트조회]]
=== Group 나의 리스트 조회

operation::my-group-list/success[snippets='http-request,http-response,response-fields']