[[Pet-API]]
== Pet API

[[Pet-등록하기]]
=== Pet 등록하기 성공
operation::add-pet/add_-pet_success[snippets='http-request,request-fields,http-response,response-fields,']

[[Pet-등록하기]]
=== Pet 등록하기 실패 1
operation::add-pet/add_-pet_fail1[snippets='http-request,http-response']

[[Pet-등록하기]]
=== Pet 등록하기 실패 2
operation::add-pet/add_-pet_fail2[snippets='http-request,http-response']

[[Pet-등록하기]]
=== Pet 등록하기 실패 3
operation::add-pet/add_-pet_fail3[snippets='http-request,http-response']

[[Pet-리스트조회]]
=== Pet 리스트 전체 조회 성공
operation::show-pet/show_-pet_-list_success[snippets='http-request,path-parameters,http-response,response-fields']

[[Pet-리스트조회]]
=== Pet 리스트 전체 조회 실패
operation::show-pet/show_-pet_-list_fail[snippets='http-request,http-response']

=== Pet 리스트 단건 조회 성공
operation::show-pet/show_-pet_success[snippets='http-request,path-parameters,http-response,response-fields']

[[Pet-리스트조회]]
=== Pet 리스트 단건 조회 실패 1
operation::show-pet/show_-pet_fail1[snippets='http-request,http-response']

[[Pet-리스트조회]]
=== Pet 리스트 단건 조회 실패 2
operation::show-pet/show_-pet_fail2[snippets='http-request,http-response']

[[Pet-수정하기]]
=== Pet 수정하기 성공
operation::update-pet/update_success[snippets='http-request,path-parameters,http-response,response-fields']

[[Pet-수정하기]]
=== Pet 수정하기 실패 1
operation::update-pet/update_fail1[snippets='http-request,http-response']

[[Pet-수정하기]]
=== Pet 수정하기 실패 2
operation::update-pet/update_fail2[snippets='http-request,http-response']

[[Pet-수정하기]]
=== Pet 수정하기 실패 3
operation::update-pet/update_fail3[snippets='http-request,http-response']

[[Pet-삭제하기]]
=== Pet 삭제하기 성공
operation::delete-pet/delete_success[snippets='http-request,path-parameters,http-response,response-fields']

[[Pet-삭제하기]]
=== Pet 삭제하기 실패 1
operation::delete-pet/delete_fail1[snippets='http-request,http-response']

[[Pet-삭제하기]]
=== Pet 삭제하기 실패 2
operation::delete-pet/delete_fail2[snippets='http-request,http-response']

[[Pet-삭제하기]]
=== Pet 삭제하기 실패 3
operation::delete-pet/delete_fail3[snippets='http-request,http-response']
